source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

pod "AFNetworking", "~> 2.0"

pod 'UIActivityIndicator-for-SDWebImage'

pod 'UMengAnalyticsSDK', '~> 3.6.5'

pod 'MagicalRecord', '~> 2.3.0'

pod 'SVPullToRefreshImprove', '~> 0.5'

pod 'TSMessages', '~> 0.9.12'